apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myredwoodtut
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: cb246735-f04c-4378-bf83-6d15bd7d0b86
  name: myredwoodtut
spec:
  ports:
  - port: 8910
    protocol: TCP
    targetPort: 8910
    #nodePort: 32233
  selector:
    app: myredwoodtut
  type: NodePort
status:
  loadBalancer: {}